version: '0.2.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./PayU.Client/src/PayU.Wrapper.Client/PayU.Wrapper.Client.csproj --verbosity m
test:
  - cmd: dotnet test ./PayU.Client/tests/PayU.Client.Tests/PayU.Client.Tests.csproj
build_script:
  - cmd: dotnet publish ./PayU.Client/src/PayU.Client/PayU.Client.csproj -c Release
  - cmd: dotnet pack ./PayU.Client/src/PayU.Client/PayU.Client.csproj -c Release
 
deploy:
  provider: NuGet
  server:
  api_key:
    secure: HX8/WaHSV+g8Ny0bJMzj8nco+2TSm1ZXrTzF1enb8loZchpY/SDgpW+0c8ucwbu4
  skip_symbols: false
  symbol_server:
  artifact: /.*\.nupkg/