version: '0.1.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./PayU.Wrapper/src/PayU.Wrapper.Client/PayU.Wrapper.Client.csproj --verbosity m
build_script:
  - cmd: dotnet publish ./PayU.Wrapper/src/PayU.Wrapper.Client/PayU.Wrapper.Client.csproj
after_build:
artifacts:
 - path: '\src\bin\Debug\netcoreapp2.0\publish'
   name: WebSite
   type: WebDeployPackage
clone_depth: 1
deploy: off