version: '0.1.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./PayU.Wrapper/src/PayU.Wrapper.Client/PayU.Wrapper.Client.csproj --verbosity m
build_script:
  - cmd: dotnet publish ./PayU.Wrapper/src/PayU.Wrapper.Client/PayU.Wrapper.Client.csproj
after_build:
artifacts:
 - path: '*/PayU.Wrapper\bin\src\*.nupkg'
   name: PayU.Wrapper.Client.1.0.0
   type: NuGetPackage  
   
#test:
#- ps: xunit.console .\PayU.Wrapper\bin\Tests\Units\netcoreapp2\PayU.Wrapper.Unit.Tests.dll /xml .\xunit-results.xml

#- ps: $wc = New-Object 'System.Net.WebClient'
#- ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit-results.xml))

clone_depth: 1
deploy: off